#+TITLE: CSCE 441 Assignment 3
#+AUTHOR: Martin Fracker
* Description
This program implements a 3D insect model with the following parts:
- Body
- Head
- 6 legs, each with 2 segments
  - Upper segment
  - Lower Segment
You can use a modal control system to modify the angles of various body parts.
* Non-Modal Control System
The camera can be rotated outside of the modal control system. That is, no
matter what mode you are in, you can rotate the camera. 

To rotate the camera, click and drag the mouse left and right.
* Modal Control System
The control system begins in =NORMAL= mode. From =NORMAL= mode, you can change
to the =HEAD=, =CAMERA=, and =LEGS= modes. From =CAMERA= mode, you can change to
the =CAMERA_PAN= mode. From =LEGS= mode, you can change from the modes =LEG1= to
=LEG6=. From each of the individual =LEG#= modes, you can switch to the
=LEG#_UPPER= and =LEG#_LOWER= for the corresponding leg.

Switching from mode to mode involves pressing a single key. You can only
traverse the modal control tree downwards, to go back up you must switch back to
=NORMAL= mode. You can switch back to =NORMAL= mode from any mode by pressing
the ~=~ key.

** Overview
Here is an overview of the modal system including the corresponding keys:
- ~=~ -> =NORMAL=
  - ~h~ -> =HEAD=
  - ~c~ -> =CAMERA=
    - ~p~ -> =CAMERA_PAN=
  - ~l~ -> =LEGS=
    - ~1~ -> =LEG1=
      - ~u~ -> =LEG1_UPPER=
      - ~l~ -> =LEG1_LOWER=
    - ~2~ -> =LEG2=
      - ~u~ -> =LEG2_UPPER=
      - ~l~ -> =LEG2_LOWER=
    - ~3~ -> =LEG3=
      - ~u~ -> =LEG3_UPPER=
      - ~l~ -> =LEG3_LOWER=
    - ~4~ -> =LEG4=
      - ~u~ -> =LEG4_UPPER=
      - ~l~ -> =LEG4_LOWER=
    - ~5~ -> =LEG5=
      - ~u~ -> =LEG5_UPPER=
      - ~l~ -> =LEG5_LOWER=
    - ~6~ -> =LEG6=
      - ~u~ -> =LEG6_UPPER=
      - ~l~ -> =LEG6_LOWER=
** Examples
Here are some examples of navigating the modal tree (note that the following
examples assume you start in =NORMAL= mode):
- to get to =LEG1_UPPER=, press the following keys in order: ~l 1 u~
- to get to =LEG6_LOWER=, press the following keys in order: ~l 6 l~
- to get to =HEAD=, press the following key: ~h~
- to get back to =NORMAL= after going to =CAMERA_PAN= mode (~c p~), simply
  press ~=~ (note this works from any mode, not just =CAMERA_PAN= mode)
** Controls within Modes
The following modes can be considered "leaf modes": =HEAD=, =CAMERA_PAN=,
=LEG#_LOWER=, and =LEG#_UPPER=. This means there is a control scheme associated
with those modes. Most of the control schemes use only the ~w~ and ~s~
keys. However, =CAMERA_PAN= mode uses all of ~w~, ~a~, ~s~, and ~d~.
*** HEAD mode
While in =HEAD= mode, the ~w~ and ~s~ keys raise and lower the head body part.
*** CAMERA_PAN mode
While in =CAMERA_PAN= mode, the ~w~, ~s~, ~a~, and ~d~ keys move the camera
forward, back, left, and right, respectively.
*** LEG#_UPPER and LEG#_LOWER modes
While in the leaf leg modes, the ~w~ and ~s~ keys raise and lower the
corresponding leg segment. For example, while in =LEG1_UPPER= mode, the ~w~ and
~s~ keys raise and lower the upper segment of the front right leg.
* Platform
- Program written and tested on Linux 64-bit.
- Requires a c++14 compatible compiler
* Makefile
Written for GCC on *nix platforms. Requires libglut, libGL, and libGLU to be in
$PATH
** Changing compile and linking flags
The Makefile can set the environment variables automatically but only if they
are not previously exported. If the Makefile seems to be broken, one or all of
the environment variables probably need to be re-exported.
#+BEGIN_SRC
$ export CXXFLAGS=-std=c++14 -I.
$ export LDFLAGS=-lglut -lGL -lGLU
$ export CXX=g++
$ make all
#+END_SRC
** Running
Run ~./main~ if it exists otherwise it must be compiled. See above if there are
compiler errors.
#+BEGIN_SRC
$ make all
$ ./main
#+END_SRC
